---
repos:
  # Disabled - broken environment
  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v24.7.0
  #   hooks:
  #     - id: ansible-lint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', 'relaxed']
        files: \.(yaml|yml)$
