---
# Test applications defaults

test_apps_namespace: test-apps

# Paths
kubeconfig_path: /etc/rancher/rke2/rke2.yaml

# Ingress domain
ingress_domain: "kube01.tanx95.us"

# Test app 1 - Simple nginx
nginx_simple_name: nginx-test
nginx_simple_host: "nginx.{{ ingress_domain }}"

# Test app 2 - Nginx with PVC
nginx_pvc_name: nginx-pvc-test
nginx_pvc_host: "nginx-pvc.{{ ingress_domain }}"
nginx_pvc_storage_size: 1Gi
